import{AlertCircle,Award,BookOpen,CheckCircle2,ChevronLeft,ClipboardCheck,Clock,GraduationCap,Layers,RefreshCw,Star,Users}from'lucide-react';
import{Link}from'react-router-dom';
import type{InstructorDashboardCourse,InstructorDashboardSubmission,StudentDashboardCourse}from'../types';

export function MetricCard({icon:Icon,label,value,detail,color}:{icon:typeof BookOpen;label:string;value:string|number;detail:string;color:string}){return <article className="dashboard-metric"><span className={`metric-icon ${color}`}><Icon/></span><div><small>{label}</small><b>{value}</b><em>{detail}</em></div></article>}

export function CourseProgressCard({course}:{course:StudentDashboardCourse}){const complete=course.nextLesson===null&&course.progress>=100;return <article className="student-course-card"><div className="student-course-cover"><span><GraduationCap/> مسار تعليمي</span><BookOpen/></div><div className="student-course-body"><div className="student-course-meta"><span>{course.instructor.name}</span><span>{course.completedLessons}/{course.totalLessons} درس</span></div><h3>{course.title}</h3><p>{course.description}</p><div className="course-progress-row"><span>التقدم</span><b>{Math.round(course.progress)}%</b></div><div className="progress"><span style={{width:`${Math.min(100,Math.max(0,course.progress))}%`}}/></div><div className="student-course-next">{complete?<><CheckCircle2/> <span>مكتملة</span></>:course.nextLesson?<><span><small>الدرس التالي</small>{course.nextLesson.title}</span></>:<span><small>المحتوى</small>لا توجد دروس بعد</span>}</div>{course.nextLesson&&!complete?<Link className="btn small course-continue" to={`/learn/courses/${course.id}/lessons/${course.nextLesson.id}`}>متابعة التعلّم <ChevronLeft/></Link>:complete?<span className="course-complete"><CheckCircle2/> اكتملت الدورة</span>:null}</div></article>}

export function InstructorCourseCard({course}:{course:InstructorDashboardCourse}){return <article className="instructor-course-card"><div className="instructor-course-head"><div><span className="course-index"><BookOpen/> دورة</span><h3>{course.title}</h3></div><span className="rating"><Star size={15} fill="currentColor"/> {course.averageRating.toFixed(1)}</span></div><div className="instructor-course-stats"><span><Users/> {course.studentsCount}<small>طلاب</small></span><span><Layers/> {course.modulesCount}<small>وحدات</small></span><span><BookOpen/> {course.lessonsCount}<small>دروس</small></span><span className={course.pendingSubmissions?'has-pending':''}><ClipboardCheck/> {course.pendingSubmissions}<small>تسليمات معلّقة</small></span></div><small className="course-created">أُنشئت في {new Date(course.createdAt).toLocaleDateString('ar-EG')}</small></article>}

export function RecentSubmissionList({submissions}:{submissions:InstructorDashboardSubmission[]}){if(!submissions.length)return <div className="dashboard-inline-empty"><ClipboardCheck/><p>لا توجد تسليمات حديثة.</p></div>;return <div className="submission-list">{submissions.map(submission=><article className="submission-item" key={submission.id}><div className="submission-avatar">{submission.student.name.slice(0,1)}</div><div className="submission-main"><b>{submission.student.name}</b><span>{submission.assignment.title} · {submission.assignment.course.title}</span><small>{new Date(submission.createdAt).toLocaleDateString('ar-EG')}</small></div><div className="submission-status">{submission.grade===null?<><span className="status pending"><Clock/> بانتظار التقييم</span><Link className="text-action" to={`/studio?submissionId=${submission.id}`}>فتح للتقييم <ChevronLeft/></Link></>:<span className="status graded"><CheckCircle2/> تم التقييم ({submission.grade})</span>}</div></article>)}</div>}

export function LoadingDashboard(){return <div className="dashboard-loading"><span/><span/><span/><span/><span/><span/></div>}
export function DashboardError({message,onRetry}:{message:string;onRetry:()=>void}){return <div className="dashboard-state error-state"><div><AlertCircle/></div><h2>تعذّر تحميل لوحة التحكم</h2><p>{message}</p><button className="btn" onClick={onRetry}><RefreshCw/> إعادة المحاولة</button></div>}
