import{Award,BookOpen,CheckCircle2,ClipboardCheck,Layers,Link as LinkIcon,Target,TrendingUp,Users}from'lucide-react';
import{Link}from'react-router-dom';
import{useCallback,useEffect,useState}from'react';
import{useAuth}from'../auth';
import{errorMessage,getInstructorDashboard,getStudentDashboard}from'../api';
import{PageHead}from'../components';
import{CourseProgressCard,DashboardError,InstructorCourseCard,LoadingDashboard,MetricCard,RecentSubmissionList}from'../dashboard/DashboardComponents';
import type{InstructorDashboardResponse,StudentDashboardResponse}from'../types';
import {AdminDashboard as PlatformAdminDashboard} from './Admin';

function useDashboard<T>(load:()=>Promise<T>){const[data,setData]=useState<T|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const retry=useCallback(()=>{setLoading(true);setError('');load().then(setData).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[load]);useEffect(()=>{retry()},[retry]);return{data,loading,error,retry}}

export function StudentDashboard({name}:{name:string}){const{data,loading,error,retry}=useDashboard<StudentDashboardResponse>(getStudentDashboard);const firstName=name.split(' ')[0];return <><PageHead eyebrow="ملخص اليوم" title={`أهلًا ${firstName}، استمر في التقدّم`} desc={loading?'نحمّل إحصاءات رحلتك التعليمية...':'تابع تقدمك الحقيقي وأنجز خطوتك التعليمية التالية.'}/>{loading?<LoadingDashboard/>:error?<DashboardError message={error} onRetry={retry}/>:data?<><div className="metric-grid"><MetricCard icon={BookOpen} color="purple" label="الدورات المسجّلة" value={data.enrolledCourses} detail="دورة في رحلتك"/><MetricCard icon={CheckCircle2} color="green" label="الدروس المكتملة" value={`${data.completedLessons}/${data.totalLessons}`} detail="درس مكتمل"/><MetricCard icon={TrendingUp} color="orange" label="متوسط التقدم" value={`${Math.round(data.averageProgress)}%`} detail="من جميع الدورات"/><MetricCard icon={Award} color="blue" label="الشهادات" value={data.certificates} detail="شهادة مكتملة"/><MetricCard icon={Target} color="purple" label="محاولات الاختبار" value={data.quizAttempts} detail="محاولة محفوظة"/><MetricCard icon={ClipboardCheck} color="orange" label="واجبات معلّقة" value={data.pendingAssignments} detail="بانتظار التسليم"/></div>{data.courses.length?<section className="panel enrolled-panel"><div className="panel-head"><div><h3>دوراتي التعليمية</h3><p>واصل التعلّم من حيث توقفت.</p></div><Link to="/learning">عرض الكل</Link></div><div className="dashboard-course-grid">{data.courses.map(course=><CourseProgressCard key={course.id} course={course}/>)}</div></section>:<div className="dashboard-state"><div><BookOpen/></div><h2>ابدأ رحلتك التعليمية</h2><p>لا توجد دورات مسجّلة لديك حاليًا. اكتشف المسارات المناسبة لأهدافك وابدأ أول خطوة.</p><Link className="btn" to="/courses">استكشف الدورات</Link></div>}</>:null}</>}

export function InstructorDashboard({name,isAdmin=false}:{name:string;isAdmin?:boolean}){const{data,loading,error,retry}=useDashboard<InstructorDashboardResponse>(getInstructorDashboard);const firstName=name.split(' ')[0],scope=isAdmin?'على مستوى المنصة بالكامل':'في دوراتك';return <><PageHead eyebrow={isAdmin?'إدارة المنصة':'مساحة المدرّس'} title={`أهلًا ${firstName}، استمر في التقدّم`} desc={loading?'نحمّل إحصاءات الدورات والتسليمات...':`${scope}، تابع الأداء والمحتوى والتسليمات من مكان واحد.`} action={<Link className="btn" to="/studio"><BookOpen/> إنشاء دورة</Link>}/>{loading?<LoadingDashboard/>:error?<DashboardError message={error} onRetry={retry}/>:data?<><div className="metric-grid"><MetricCard icon={BookOpen} color="purple" label="إجمالي الدورات" value={data.coursesCount} detail={scope}/><MetricCard icon={Users} color="green" label="الطلاب" value={data.studentsCount} detail="طلاب مسجّلون بشكل فريد"/><MetricCard icon={BookOpen} color="blue" label="الدروس" value={data.lessonsCount} detail={scope}/><MetricCard icon={TrendingUp} color="orange" label="متوسط التقييم" value={data.averageRating.toFixed(1)} detail="من 5"/><MetricCard icon={ClipboardCheck} color="purple" label="تسليمات معلّقة" value={data.pendingSubmissions} detail="بانتظار التقييم"/></div><div className="instructor-dashboard-grid"><section className="panel"><div className="panel-head"><div><h3>{isAdmin?'الدورات على مستوى المنصة':'دوراتك التعليمية'}</h3><p>إحصاءات حقيقية محدثة من النظام.</p></div></div>{data.courses.length?<div className="instructor-course-grid">{data.courses.map(course=><InstructorCourseCard key={course.id} course={course}/>)}</div>:<div className="dashboard-inline-empty"><Layers/><p>{isAdmin?'لا توجد دورات على المنصة بعد.':'لا توجد دورات مرتبطة بحسابك بعد.'}</p></div>}</section><section className="panel"><div className="panel-head"><div><h3>أحدث التسليمات</h3><p>آخر ملفات الطلاب المسجّلة.</p></div></div><RecentSubmissionList submissions={data.recentSubmissions}/></section></div></>:null}</>}

export function Dashboard(){const{user}=useAuth();if(!user)return null;if(user.role==='STUDENT')return <StudentDashboard name={user.name}/>;if(user.role==='ADMIN')return <PlatformAdminDashboard/>;return <InstructorDashboard name={user.name}/>}
