import{Award,BookOpen,CheckCircle2,ChevronLeft,GraduationCap,RefreshCw,Star,Users}from'lucide-react';
import{Link}from'react-router-dom';
import{useCallback,useEffect,useState}from'react';
import{errorMessage,generateCertificate,getEnrolledCourses}from'../api';
import{PageHead,Pagination}from'../components';
import type {EnrolledCourse,Pagination as PaginationMeta}from'../types';

function LearningSkeleton(){return <div className="learning-skeleton-grid">{[1,2,3].map(item=><div className="learning-skeleton-card" key={item}><span/><div><i/><i/><i/></div></div>)}</div>}
function LearningError({message,retry}:{message:string;retry:()=>void}){return <div className="learning-state learning-error"><div><RefreshCw/></div><h2>تعذّر تحميل دوراتك</h2><p>{message}</p><button className="btn" onClick={retry}><RefreshCw/> إعادة المحاولة</button></div>}
function LearningEmpty(){return <div className="learning-state"><div><GraduationCap/></div><h2>لم تبدأ رحلتك بعد</h2><p>لا توجد دورات مسجّلة لديك حاليًا. استكشف المسارات العملية واختر ما يناسب أهدافك.</p><Link className="btn" to="/courses">استكشف الدورات <ChevronLeft/></Link></div>}

function EnrolledCourseCard({course,onCertificateIssued}:{course:EnrolledCourse;onCertificateIssued:(courseId:number,certificate:EnrolledCourse['certificate'])=>void}){
 const complete=course.nextLesson===null&&course.progress>=100;
 const[issuing,setIssuing]=useState(false),[issueError,setIssueError]=useState('');
 async function issueCertificate(){setIssuing(true);setIssueError('');try{const certificate=await generateCertificate(course.id);onCertificateIssued(course.id,certificate)}catch(e){setIssueError(errorMessage(e))}finally{setIssuing(false)}}
 return <article className="learning-course-card"><div className="learning-course-cover"><span><GraduationCap/> مسار تعليمي</span><BookOpen/></div><div className="learning-course-body"><div className="learning-course-meta"><span><Users/> {course.instructor.name}</span><span><Star fill="currentColor"/> {course.averageRating?course.averageRating.toFixed(1):'جديد'}</span></div><h2>{course.title}</h2><p className="learning-description">{course.description}</p><div className="learning-progress-label"><span>تقدمك في الدورة</span><b>{Math.round(course.progress)}%</b></div><div className="progress"><span style={{width:`${Math.min(100,Math.max(0,course.progress))}%`}}/></div><div className="learning-lessons-count"><BookOpen/> {course.completedLessons} من {course.totalLessons} درس مكتمل</div>{course.nextLesson?<div className="learning-next"><small>الدرس التالي</small><strong>{course.nextLesson.title}</strong></div>:complete?<div className="learning-complete"><CheckCircle2/> اكتملت الدورة</div>:<div className="learning-next"><small>المحتوى</small><strong>لا توجد دروس متاحة بعد</strong></div>}{issueError&&<p className="learning-inline-error">{issueError}</p>}<div className="learning-actions">{course.nextLesson&&!complete?<Link className="btn" to={`/learn/courses/${course.id}/lessons/${course.nextLesson.id}`}>متابعة التعلّم <ChevronLeft/></Link>:course.certificate?.url?<a className="btn certificate-btn" href={course.certificate.url} target="_blank" rel="noreferrer"><Award/> عرض الشهادة</a>:complete&&!course.certificate?<button className="btn certificate-btn" onClick={issueCertificate} disabled={issuing}><Award/> {issuing?'جاري الإصدار...':'إصدار الشهادة'}</button>:null}<Link className="text-link" to={`/learn/courses/${course.id}`}>عرض الدورة <ChevronLeft/></Link></div></div></article>
}

export function Learning(){const[courses,setCourses]=useState<EnrolledCourse[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(1),[meta,setMeta]=useState<PaginationMeta>({page:1,limit:6,totalItems:0,totalPages:0,hasPreviousPage:false,hasNextPage:false});const load=useCallback(()=>{setLoading(true);setError('');getEnrolledCourses({page,limit:6}).then(result=>{setCourses(result.data);setMeta(result.pagination)}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[page]);useEffect(()=>{load()},[load]);function onCertificateIssued(courseId:number,certificate:EnrolledCourse['certificate']){setCourses(current=>current.map(course=>course.id===courseId?{...course,certificate}:course))}return <><PageHead eyebrow="مساحتي التعليمية" title="تعلّمي" desc="تابعي دوراتك، راقبي تقدمك، وواصلي التعلم من حيث توقفت."/><div className="learning-toolbar"><span><BookOpen/> {loading?'...':meta.totalItems} دورة مسجّلة</span><Link className="btn small" to="/courses">اكتشاف دورات جديدة</Link></div>{loading?<LearningSkeleton/>:error?<LearningError message={error} retry={load}/>:courses.length===0?<LearningEmpty/>:<><div className="learning-course-grid">{courses.map(course=><EnrolledCourseCard key={course.id} course={course} onCertificateIssued={onCertificateIssued}/>)}</div><Pagination {...meta} currentPage={meta.page} totalPages={meta.totalPages} onPageChange={setPage}/></>}</>}
