import {Award,BookOpen,Home,LayoutDashboard,LogOut,Menu,GraduationCap,PlusCircle,X,ArrowUpLeft,Star,Users,Layers,type LucideIcon} from 'lucide-react'; import {NavLink,Navigate,Outlet,useLocation} from 'react-router-dom'; import {useState,type ReactNode} from 'react'; import {useAuth} from './auth'; import type {Course,Role} from './types';
type ShellLink=[string,string,LucideIcon];
const navigationByRole:Record<Role,ShellLink[]>={STUDENT:[['/dashboard','لوحة التحكم',LayoutDashboard],['/learning','تعلّمي',GraduationCap],['/certificates','شهاداتي',Award]],INSTRUCTOR:[['/dashboard','لوحة التحكم',LayoutDashboard],['/studio','استوديو المدرّس',PlusCircle]],ADMIN:[['/admin','لوحة الإدارة',LayoutDashboard],['/admin/users','إدارة المستخدمين',Users],['/admin/courses','إدارة الدورات',BookOpen],['/admin/enrollments','التسجيلات',Layers],['/admin/submissions','التسليمات',BookOpen],['/admin/certificates','الشهادات',Award],['/admin/reviews','التقييمات',Star]]};
export function Shell(){const {user,logout}=useAuth();const [open,setOpen]=useState(false);const links:ShellLink[]=[['/','الرئيسية',Home],['/courses','استكشف الدورات',BookOpen],...(user?(navigationByRole[user.role]||[]):[])];return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><span className="brandmark">N</span><div><b>NexaLearn</b><small>{user?.role==='ADMIN'?'إدارة المنصة':'مساحتك للتقدّم'}</small></div></div><button className="close" onClick={()=>setOpen(false)}><X/></button><nav>{links.map(([to,label,Icon])=><NavLink key={to} to={to} end onClick={()=>setOpen(false)}><Icon size={19}/><span>{label}</span></NavLink>)}</nav><div className="sidecard"><div className="orb">✦</div><b>{user?.role==='ADMIN'?'إدارة المنصة':'تعلّم بلا حدود'}</b><p>{user?.role==='ADMIN'?'أدر المستخدمين والمحتوى والتقارير من مكان واحد.':'مسارات عملية وتجربة تعليمية مصممة للنتائج.'}</p></div>{user&&<button className="logout" onClick={logout}><LogOut size={18}/>تسجيل الخروج</button>}</aside><main><header><button className="menubtn" onClick={()=>setOpen(true)}><Menu/></button><div className="header-title"><b>منصة التعلّم المؤسسي</b><small>تعلّم. طبّق. تقدّم.</small></div><div className="userbox">{user?<><span className="avatar">{user.name.slice(0,1)}</span><div><b>{user.name}</b><small>{roleLabel(user.role)}</small></div></>:<NavLink className="btn small" to="/login">تسجيل الدخول</NavLink>}</div></header><div className="content"><Outlet/></div></main></div>}
export function Protected({roles}:{roles?:Role[]}){const {user}=useAuth();const location=useLocation();if(!user)return <Navigate to="/login" replace state={{from:location.pathname}}/>;if(roles&&!roles.includes(user.role))return <Navigate to={user.role==='ADMIN'?'/admin':'/dashboard'} replace/>;return <Outlet/>}
export const roleLabel=(r:Role)=>({ADMIN:'مدير النظام',INSTRUCTOR:'مدرّس',STUDENT:'طالب'}[r]);
export function PageHead({eyebrow,title,desc,action}:{eyebrow:string;title:string;desc:string;action?:ReactNode}){return <div className="pagehead"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
export function CourseCard({c}:{c:Course}){return <NavLink to={`/courses/${c.id}`} className="course-card"><div className="course-cover"><span>المسار {String(c.id).padStart(2,'0')}</span><BookOpen size={42}/></div><div className="course-body"><div className="course-meta"><span><Star size={15} fill="currentColor"/> {c.averageRating||'جديد'}</span><span><Users size={15}/>{c._count?.enrollments||0} طالب</span></div><h3>{c.title}</h3><p>{c.description}</p><div className="course-foot"><span className="teacher">{c.instructor?.name||'مدرّس NexaLearn'}</span><b>{Number(c.price)===0?'مجاني':`${Number(c.price).toLocaleString()} ج.م`}</b></div></div></NavLink>}
export function Empty({title,desc}:{title:string;desc:string}){return <div className="empty"><div><Layers/></div><h3>{title}</h3><p>{desc}</p></div>}
export function Toast({text,type='ok'}:{text:string;type?:'ok'|'error'}){return <div className={`toast ${type}`}>{text}</div>}
export function Back(){return <button className="back" onClick={()=>history.back()}><ArrowUpLeft/> رجوع</button>}
export function Pagination({currentPage,totalPages,hasPreviousPage,hasNextPage,onPageChange,disabled=false}:{currentPage:number;totalPages:number;hasPreviousPage:boolean;hasNextPage:boolean;onPageChange:(page:number)=>void;disabled?:boolean}){const pages=Array.from({length:totalPages},(_,i)=>i+1).filter(p=>p===1||p===totalPages||Math.abs(p-currentPage)<=1);const items:(number|'ellipsis')[]=[];pages.forEach((p,i)=>{if(i&&p-pages[i-1]>1)items.push('ellipsis');items.push(p)});return <div className="pagination" aria-label="التنقل بين الصفحات"><button disabled={disabled||!hasNextPage} onClick={()=>onPageChange(currentPage+1)} aria-label="الصفحة التالية">←</button>{items.map((p,i)=>p==='ellipsis'?<span key={`e${i}`}>…</span>:<button key={p} disabled={disabled} className={p===currentPage?'active':''} onClick={()=>onPageChange(p)} aria-current={p===currentPage?'page':undefined}>{p}</button>)}<button disabled={disabled||!hasPreviousPage} onClick={()=>onPageChange(currentPage-1)} aria-label="الصفحة السابقة">→</button></div>}
